# This file either runs with JetBrains' http requests or using httpYac (https://httpyac.github.io).

### Create account
POST http://127.0.0.1:4000/accounts

> {%
    client.test("status", function() {
        client.assert(response.status === 200, "Response status is not 200");
        client.global.set("account_id", response.body.toString());
    });
%}


### Insert email
POST http://127.0.0.1:4000/property-types
Content-Type: application/json
Accept: application/json

{
  "ownedById": "{{account_id}}",
  "actorId": "{{account_id}}",
  "schema": 
  {
    "$schema": "https://blockprotocol.org/types/modules/graph/0.3/schema/property-type",
    "kind": "propertyType",
    "$id": "https://blockprotocol.org/@alice/types/property-type/email/v/1",
    "title": "Email",
    "oneOf": [
      {
        "$ref": "https://blockprotocol.org/@blockprotocol/types/data-type/text/v/1"
      }
    ]
  }
}

### Insert email
POST http://127.0.0.1:4000/property-types
Content-Type: application/json
Accept: application/json

{
  "ownedById": "{{account_id}}",
  "actorId": "{{account_id}}",
  "schema": {
    "$schema": "https://blockprotocol.org/types/modules/graph/0.3/schema/property-type",
    "kind": "propertyType",
    "$id": "http://localhost:3000/@alice/types/property-type/email/v/1",
    "title": "Email",
    "oneOf": [
      {
        "$ref": "https://blockprotocol.org/@blockprotocol/types/data-type/text/v/1"
      }
    ]
  }
}

### Insert phone number
POST http://127.0.0.1:4000/property-types
Content-Type: application/json
Accept: application/json

{
  "ownedById": "{{account_id}}",
  "actorId": "{{account_id}}",
  "schema": {
    "$schema": "https://blockprotocol.org/types/modules/graph/0.3/schema/property-type",
    "kind": "propertyType",
    "$id": "http://localhost:3000/@alice/types/property-type/phone-number/v/1",
    "title": "Phone Number",
    "oneOf": [
      {
        "$ref": "https://blockprotocol.org/@blockprotocol/types/data-type/text/v/1"
      }
    ]
  }
}

### Insert contact information
POST http://127.0.0.1:4000/property-types
Content-Type: application/json
Accept: application/json

{
  "ownedById": "{{account_id}}",
  "actorId": "{{account_id}}",
  "schema": {
  "$schema": "https://blockprotocol.org/types/modules/graph/0.3/schema/property-type",
    "kind": "propertyType",
    "$id": "http://localhost:3000/@alice/types/property-type/contact-information/v/1",
    "title": "Contact Information",
    "oneOf": [
      {
        "type": "object",
        "properties": {
          "http://localhost:3000/@alice/types/property-type/email/": {
            "$ref": "http://localhost:3000/@alice/types/property-type/email/v/1"
          },
          "http://localhost:3000/@alice/types/property-type/phone-number/": {
            "$ref": "http://localhost:3000/@alice/types/property-type/phone-number/v/1"
          }
        },
        "required": [
          "http://localhost:3000/@alice/types/property-type/email/"
        ]
      }
    ]
  }
}

### Insert contact information entity type
POST http://127.0.0.1:4000/entity-types
Content-Type: application/json
Accept: application/json

{
  "ownedById": "{{account_id}}",
  "actorId": "{{account_id}}",
  "schema": {
  "$schema": "https://blockprotocol.org/types/modules/graph/0.3/schema/entity-type",
    "$id": "http://localhost:3000/@examples/types/entity-type/person/v/1",
    "kind": "entityType",
    "title": "Person",
    "type": "object",
    "allOf": [],
    "description": "An extremely simplified representation of a person or human being.",
    "examples": [],
    "links": {
      "https://blockprotocol.org/@examples/types/entity-type/employed-by/v/1": {
        "type": "array",
        "minItems": 0,
        "ordered": false,
        "items": {
          "oneOf": [
            {
              "$ref": "https://blockprotocol.org/@examples/types/entity-type/company/v/1"
            }
          ]
        }
      }
    },
    "properties": {
      "http://localhost:3000/@alice/types/property-type/contact-information/": {
        "$ref": "http://localhost:3000/@alice/types/property-type/contact-information/v/1"
      }
    },
    "required": [
      "http://localhost:3000/@alice/types/property-type/contact-information/"
    ]
  }
}
